name: fraud_detection_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip>=23.0
  - pip:
      - mlflow==2.19.0
      - pandas==2.1.4
      - numpy==1.26.2
      - scikit-learn==1.3.2
      - imbalanced-learn==0.12.0
      - matplotlib==3.8.2
      - seaborn==0.13.0
